# Generated by Django 2.2.1 on 2019-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0002_auto_20190616_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Алиас'),
        ),
    ]
