# Generated by Django 2.2.1 on 2019-06-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0004_adverts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adverts',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
